name: 'test'
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          go test -v ./...
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: JetBrains/code-analytics-examples
          path: ./projects
      - run: |
          go run main.go scan -i ./projects/js/
          ls -la .qodana/
          [ -f .qodana/results/qodana.sarif.json ] || fail "No qodana.sarif.json created"
