name: 'Test'
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          go test -v ./...
