name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'install.ps1'
      - 'install'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'install.ps1'
      - 'install'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest