name: Qodana
on:
  workflow_dispatch:
  pull_request:
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Qodana'
        uses: JetBrains/qodana-action@main
