name: 'winget release'
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: JetBrains.QodanaCLI
          token: ${{ secrets.WINGET_GH_PAT_TOKEN }}
          release-tag: v2023.1.5
          fork-user: tiulpin